"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from . import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ModemPresetInfo(_message.Message):
    """
    Modem Preset Registry

    NOT used on-wire; consumed by clients/apps and optionally embedded in firmware.
    Centralizes the radio parameters of each ModemPreset. Which presets a region
    permits, and whether that needs a licensed operator, is region data in
    region_registry.proto.

    Data lives in registry/modem_presets.yaml. tools/gen_registry.py validates it
    and generates registry/generated/modem_presets.json, which `buf convert`
    serializes.
    Firmware can generate its modem config table from this data or embed it directly.


    Complete definition of a single modem preset
    """

    DESCRIPTOR: _descriptor.Descriptor

    PRESET_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    BANDWIDTH_HZ_FIELD_NUMBER: _builtins.int
    WIDE_BANDWIDTH_HZ_FIELD_NUMBER: _builtins.int
    SPREAD_FACTOR_FIELD_NUMBER: _builtins.int
    CODING_RATE_FIELD_NUMBER: _builtins.int
    preset: _common_pb2.ModemPreset.ValueType
    """Which preset this defines"""
    name: _builtins.str
    """
    The preset's name, and the only place it is written: firmware displays this string,
    e.g. "LongFast", "ShortTurbo", and a primary channel with an empty name is named by
    it. Because LoRaConfig.channel_num can hash it, changing one of these names moves
    every node whose channel took its default from that preset.
    """
    bandwidth_hz: _builtins.int
    """
    Nominal bandwidth in Hz in a sub-GHz region (e.g. 125000, 62500, 15600), the slot
    plan's input. The radio may synthesise a slightly different value, 15625 for 15600.
    """
    wide_bandwidth_hz: _builtins.int
    """
    Nominal bandwidth in Hz in a wide LoRa region (RegionInfo.wide_lora, above 1 GHz),
    e.g. 812500. 0 = the preset has no wide form, and no wide region permits it.
    """
    spread_factor: _builtins.int
    """Spreading factor (5-12)"""
    coding_rate: _builtins.int
    """Coding rate denominator (5-8, i.e. 4/5 through 4/8)"""
    def __init__(
        self,
        *,
        preset: _common_pb2.ModemPreset.ValueType = ...,
        name: _builtins.str = ...,
        bandwidth_hz: _builtins.int = ...,
        wide_bandwidth_hz: _builtins.int = ...,
        spread_factor: _builtins.int = ...,
        coding_rate: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bandwidth_hz", b"bandwidth_hz", "coding_rate", b"coding_rate", "name", b"name", "preset", b"preset", "spread_factor", b"spread_factor", "wide_bandwidth_hz", b"wide_bandwidth_hz"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModemPresetInfo: _TypeAlias = ModemPresetInfo  # noqa: Y015

@_typing.final
class BandwidthCode(_message.Message):
    """
    A LoRaConfig.bandwidth wire code and the nominal bandwidth it stands for
    """

    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    BANDWIDTH_HZ_FIELD_NUMBER: _builtins.int
    code: _builtins.int
    """The value of LoRaConfig.bandwidth"""
    bandwidth_hz: _builtins.int
    """Nominal bandwidth in Hz, the slot plan's input for a custom setting"""
    def __init__(
        self,
        *,
        code: _builtins.int = ...,
        bandwidth_hz: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bandwidth_hz", b"bandwidth_hz", "code", b"code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BandwidthCode: _TypeAlias = BandwidthCode  # noqa: Y015

@_typing.final
class ModemPresetRegistry(_message.Message):
    """
    The complete modem preset registry
    """

    DESCRIPTOR: _descriptor.Descriptor

    PRESETS_FIELD_NUMBER: _builtins.int
    REVISION_FIELD_NUMBER: _builtins.int
    BANDWIDTH_CODES_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """
    Raised by every change to the data. CI rejects a change that leaves it where it
    was, so a client can tell whether its bundled copy is current.
    """
    @_builtins.property
    def presets(self) -> _containers.RepeatedCompositeFieldContainer[Global___ModemPresetInfo]:
        """Every preset with a definition"""

    @_builtins.property
    def bandwidth_codes(self) -> _containers.RepeatedCompositeFieldContainer[Global___BandwidthCode]:
        """
        LoRaConfig.bandwidth codes and their nominal bandwidths: every code that stands for
        something other than its value in kHz, and the whole-kHz ones radios use. A code
        not listed is kHz as it stands.
        """

    def __init__(
        self,
        *,
        presets: _abc.Iterable[Global___ModemPresetInfo] | None = ...,
        revision: _builtins.int = ...,
        bandwidth_codes: _abc.Iterable[Global___BandwidthCode] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bandwidth_codes", b"bandwidth_codes", "presets", b"presets", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModemPresetRegistry: _TypeAlias = ModemPresetRegistry  # noqa: Y015
