name: Publish to pypi
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
# TODO: when working, try adding this
#    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Uninstall meshtastic
        run: |
          pip3 uninstall meshtastic
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install pdoc3 pygatt pandoc twine nanopb
# TODO: update proto
# TODO: gen docs
#      - name: Generate docs
#        run: |
#          rm -f dist/*
#          set -e
#          bin/regen-docs.sh
#          pandoc --from=markdown --to=rst --output=README README.md
#
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
